### ISSUE TITLE
[BUG] Respawn Obelisks Crashes on Startup With IguanaTweaks Reborn Installed.

### ISSUE THREAD

**Issue by CraftyZombie** [RedPxnda/RespawnObelisks#11] opened 2024-01-14 00:00 UTC
**Describe the bug**
The game crashes on startup when IguanaTweaks Reborn is installed with Respawn Obelisks.

**To Reproduce**
1. Start up the game.

**Expected behavior**
The game should load as normal.

**Versions**
IguanaTweaks Reborn: 3.0.4-mc1.20.1
InsaneLib: 1.12.1
Architectury 9.1.12
MaxHealthFix 12.0.2
Resourceful Config 2.1.2
Respawn Obelisks 2.4-c

Forge Version: 47.2.19
Minecraft Version: 1.20.1

**Additional notes**
latest.log and debug.log: (https://gist.github.com/CraftyZombie/eb10f481233ffe10e9646d861e5362c9)
(No crash report is generated.)

**Comment by CraftyZombie** [comment] 2024-01-14 00:01
For reference, I also made this post on the IguanaTweaks Reborn Github.

https://github.com/Insane96/IguanaTweaksReborn/issues/261

**Comment by RedPxnda** [comment] 2024-01-14 00:34
These appears to be caused by the way IguanaTweaks Reborn includes EvalEx, a dependency both RespawnObelisks(technically Nucleus, which is the main embedded library of RespawnObelisks) and ITR use. (ITR uses the gradle shadow plugin to include it, instead of the intended forge native system: Jar-in-jar)
Technically, this will be fixed if I update to a newer version of Nucleus, since it no longer depends on EvalEx, but ehhh

**Comment by CraftyZombie** [comment] 2024-01-14 00:36
I see.

Is that a big pain to do? I get if it's a whole thing.

**Comment by RedPxnda** [comment] 2024-01-14 00:45
Nah, it's really easy, I'm doing it right now- should be fixed in 2.4-d(should be published to CF and Modrinth in a few hours), although I still do recommend the author of ITR fixes this on their end to maintain compat with any other mods that use EvalEx.

**Closed as completed by RedPxnda** 2024-01-14 00:45 UTC

**Comment by CraftyZombie** [comment] 2024-01-14 00:46
Noted. Thank you so much!

**Comment by Insane96** [comment] 2024-01-14 09:44
Back in the day, I saw no mods using EvalEx, and didn't manage to make Jar-in-Jar work, so I've gone the shadow way. I will try again once I port my mods past 1.20.1 with Norge

**Comment by CraftyZombie** [comment] 2024-01-16 03:44
Appreciated.
