### ISSUE TITLE
[BUG] Incompatibility with Relics' Magic Mirror item

### ISSUE THREAD

**Issue by Not-February** [RedPxnda/RespawnObelisks#8] opened 2023-11-30 11:39 UTC
**Describe the bug**
The Magic Mirror from the Relics mod does not function with Respawn Obelisks installed.

**To Reproduce**
1. Have both Respawn Obelisks and Relics installed
2. Set your respawn point with a Respawn Obelisk
3. Use Magic Mirror
4. Nothing happens

**Expected behavior**
The Magic Mirror is supposed to bring you back to your spawn point when used within a specified allowed radius, but doesn't. I personally wonder if it is for similar reasons to https://github.com/AstralOrdana/Spelunkery/issues/86 but don't really know for sure, since I don't know how to check that for myself.
As a comparison point, setting one's spawnpoint manually with the /spawnpoint command allows the mirror to work as expected.

**Versions**
 - Respawn Obelisk 2.4-b
 - Forge Version 47.2.0
 - Minecraft 1.20.1

**Comment by RedPxnda** [comment] 2023-11-30 11:52
Yes, this is unfortunately(but in some ways, fortunately?) caused by the same thing as the spelunkery bug. I have to rethink the way I evaluate the player's spawn, and I have some ideas to do so, but I need to see if they have any unwanted side effects first.

**Comment by CraftyZombie** [comment] 2024-01-23 01:06
I'd like to add that this takes the form of a third issue with Enigmatic Legacy.
It has an item called the Scroll of Postmortal Recall, which returns your inventory to your spawnpoint upon death.
This feature is not compatible with Respawn Obelisks.

**Comment by RedPxnda** [comment] 2024-01-23 01:07
yep, same issue with all of these. Will be fixed next [major] update(2.5), although that requires me to find a good fix first...

**Comment by CraftyZombie** [comment] 2024-01-23 02:26
What's the problem with using Vanilla's implementation again?

**Comment by RedPxnda** [comment] 2024-01-23 02:30
The method that it uses (to calculate spawn position based on the block at the set spawn) doesn't provide the player, despite being accessible in the only place it's used.
TBH, I think this was a mistake, but it doesn't really matter for vanilla anyways. (Basically the method is inside the Player class, yet is static- I believe the intention was for it to be non-static but it didn't really matter for vanilla)
So somehow, I need to store the player currently respawning(that also works with other mods!) in a sensible manner that works in multiplayer.

**Comment by CraftyZombie** [comment] 2024-01-23 03:41
Got it.

**Comment by RedPxnda** [comment] 2024-03-06 02:40
Will be fixed(hopefully) in the next update.

**Closed as completed by RedPxnda** 2024-03-06 02:40 UTC
